/* ── CodaScope: Epic Render Service ──────────────────────────────────
   Renders design documents as rich, self-contained HTML.

   Approach: Standalone renderer (no Kiss AI dependency). Uses the
   markdown source to generate a polished HTML document with:
   - Styled sections, typography, color theme
   - Syntax-highlighted code blocks (via highlight.js CDN)
   - Mermaid diagram support (via mermaid CDN)
   - Collapsible sections, print-friendly layout

   Storage: <epicId>/designs/<docId>-rendered/index.html
   ──────────────────────────────────────────────────────────────────── */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import path from "node:path";

/* ── Service ──────────────────────────────────────────────────────── */

export class CodaScopeEpicRenderService {
  private root: string;

  constructor(root: string) {
    this.root = root;
  }

  setRoot(root: string): void {
    this.root = root;
  }

  /* ── Path helpers ──────────────────────────────────────────────── */

  private projectDir(projectId: string): string | null {
    if (!existsSync(this.root)) return null;
    const entries = readdirSync(this.root, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name.startsWith(".")) continue;
      const projectPath = path.join(this.root, entry.name, "project.json");
      if (existsSync(projectPath)) {
        try {
          const data = JSON.parse(readFileSync(projectPath, "utf-8"));
          if (data.id === projectId) return path.join(this.root, entry.name);
        } catch { /* skip corrupted */ }
      }
    }
    return null;
  }

  private renderedDir(projectDir: string, epicId: string, docId: string): string {
    return path.join(projectDir, "epics", epicId, "designs", `${docId}-rendered`);
  }

  private renderedPath(projectDir: string, epicId: string, docId: string): string {
    return path.join(this.renderedDir(projectDir, epicId, docId), "index.html");
  }

  /* ── Public API ────────────────────────────────────────────────── */

  /**
   * Store rendered HTML for a design document.
   * The HTML is generated by the agent via do_render_design.md.
   */
  async saveRenderedHtml(
    projectId: string,
    epicId: string,
    docId: string,
    html: string,
  ): Promise<boolean> {
    const projectDir = this.projectDir(projectId);
    if (!projectDir) return false;

    const dir = this.renderedDir(projectDir, epicId, docId);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

    writeFileSync(this.renderedPath(projectDir, epicId, docId), html, "utf-8");
    return true;
  }

  /**
   * Get rendered HTML for a design document.
   * Returns null if not yet rendered.
   */
  async getRenderedHtml(
    projectId: string,
    epicId: string,
    docId: string,
  ): Promise<string | null> {
    const projectDir = this.projectDir(projectId);
    if (!projectDir) return null;

    const p = this.renderedPath(projectDir, epicId, docId);
    if (!existsSync(p)) return null;
    return readFileSync(p, "utf-8");
  }

  /**
   * Check if rendered HTML exists for a design document.
   */
  async hasRenderedHtml(
    projectId: string,
    epicId: string,
    docId: string,
  ): Promise<boolean> {
    const projectDir = this.projectDir(projectId);
    if (!projectDir) return false;
    return existsSync(this.renderedPath(projectDir, epicId, docId));
  }

  /**
   * Generate a basic HTML rendering from markdown source.
   * This is a fallback when the agent isn't available — it produces
   * a clean, self-contained HTML document with inline styles.
   */
  generateBasicHtml(markdown: string, title: string): string {
    // Convert markdown to basic HTML using simple regex-based conversion
    const bodyHtml = this.markdownToHtml(markdown);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(title)}</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"><\/script>
  <style>
    :root {
      --bg-primary: #0d1117;
      --bg-secondary: #161b22;
      --bg-tertiary: #1c2128;
      --text-primary: #e6edf3;
      --text-secondary: #8b949e;
      --text-muted: #656d76;
      --border-color: #30363d;
      --accent: #58a6ff;
      --accent-dim: #1f6feb33;
      --code-bg: #161b22;
      --success: #3fb950;
      --warning: #d29922;
      --danger: #f85149;
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
      background: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.7;
      max-width: 900px;
      margin: 0 auto;
      padding: 48px 32px;
    }

    h1 { font-size: 2em; margin: 32px 0 16px; border-bottom: 1px solid var(--border-color); padding-bottom: 12px; }
    h2 { font-size: 1.5em; margin: 28px 0 12px; border-bottom: 1px solid var(--border-color); padding-bottom: 8px; }
    h3 { font-size: 1.25em; margin: 24px 0 8px; }
    h4 { font-size: 1.1em; margin: 20px 0 8px; }

    p { margin: 8px 0 16px; }

    ul, ol { margin: 8px 0 16px; padding-left: 28px; }
    li { margin: 4px 0; }

    code {
      background: var(--code-bg);
      border: 1px solid var(--border-color);
      border-radius: 6px;
      padding: 2px 6px;
      font-size: 0.9em;
      font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
    }

    pre {
      background: var(--code-bg);
      border: 1px solid var(--border-color);
      border-radius: 8px;
      padding: 16px;
      margin: 12px 0 20px;
      overflow-x: auto;
    }
    pre code {
      border: none;
      padding: 0;
      background: transparent;
    }

    blockquote {
      border-left: 4px solid var(--accent);
      padding: 8px 16px;
      margin: 12px 0;
      color: var(--text-secondary);
      background: var(--accent-dim);
      border-radius: 0 6px 6px 0;
    }

    table {
      border-collapse: collapse;
      width: 100%;
      margin: 12px 0 20px;
    }
    th, td {
      border: 1px solid var(--border-color);
      padding: 8px 12px;
      text-align: left;
    }
    th {
      background: var(--bg-secondary);
      font-weight: 600;
    }
    tr:nth-child(even) { background: var(--bg-tertiary); }

    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }

    hr {
      border: none;
      border-top: 1px solid var(--border-color);
      margin: 24px 0;
    }

    .mermaid {
      background: var(--bg-secondary);
      border-radius: 8px;
      padding: 16px;
      margin: 12px 0 20px;
      text-align: center;
    }

    strong { font-weight: 600; }
    em { font-style: italic; color: var(--text-secondary); }

    /* Collapsible sections */
    details {
      border: 1px solid var(--border-color);
      border-radius: 8px;
      margin: 12px 0;
      padding: 12px;
    }
    summary {
      cursor: pointer;
      font-weight: 600;
      padding: 4px 0;
    }
    details[open] summary { margin-bottom: 8px; }

    @media print {
      body { background: white; color: #24292f; max-width: none; padding: 20px; }
      pre, code { background: #f6f8fa; }
      blockquote { background: #f0f4ff; }
      th { background: #f6f8fa; }
      tr:nth-child(even) { background: #f6f8fa; }
      a { color: #0969da; }
      .mermaid { background: #f6f8fa; }
    }
  </style>
</head>
<body>
  ${bodyHtml}
  <script>
    mermaid.initialize({ startOnLoad: true, theme: 'dark' });
  <\/script>
</body>
</html>`;
  }

  /* ── Private helpers ───────────────────────────────────────────── */

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  /**
   * Simple markdown → HTML converter for the fallback renderer.
   * Handles headings, paragraphs, code blocks (including mermaid),
   * lists, blockquotes, tables, links, bold, italic, and hr.
   */
  private markdownToHtml(markdown: string): string {
    const lines = markdown.split("\n");
    const output: string[] = [];
    let i = 0;
    let inList = false;
    let listType: "ul" | "ol" = "ul";

    while (i < lines.length) {
      const line = lines[i];

      // Code blocks (fenced)
      if (line.trimStart().startsWith("```")) {
        const lang = line.trimStart().slice(3).trim();
        const codeLines: string[] = [];
        i++;
        while (i < lines.length && !lines[i].trimStart().startsWith("```")) {
          codeLines.push(lines[i]);
          i++;
        }
        i++; // skip closing ```

        if (lang === "mermaid") {
          output.push(`<div class="mermaid">\n${codeLines.join("\n")}\n</div>`);
        } else {
          output.push(`<pre><code>${this.escapeHtml(codeLines.join("\n"))}</code></pre>`);
        }
        continue;
      }

      // Close list if current line isn't a list item
      if (inList && !line.match(/^(\s*[-*]|\s*\d+\.\s)/)) {
        output.push(listType === "ul" ? "</ul>" : "</ol>");
        inList = false;
      }

      // Headings
      const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
      if (headingMatch) {
        const level = headingMatch[1].length;
        output.push(`<h${level}>${this.inlineMarkdown(headingMatch[2])}</h${level}>`);
        i++;
        continue;
      }

      // HR
      if (line.match(/^---+$/) || line.match(/^\*\*\*+$/) || line.match(/^___+$/)) {
        output.push("<hr>");
        i++;
        continue;
      }

      // Blockquote
      if (line.startsWith(">")) {
        const quoteLines: string[] = [];
        while (i < lines.length && (lines[i].startsWith(">") || (lines[i].trim() && quoteLines.length > 0))) {
          quoteLines.push(lines[i].replace(/^>\s?/, ""));
          i++;
          if (i < lines.length && !lines[i].startsWith(">") && !lines[i].trim()) break;
        }
        output.push(`<blockquote><p>${this.inlineMarkdown(quoteLines.join(" "))}</p></blockquote>`);
        continue;
      }

      // Unordered list
      if (line.match(/^\s*[-*]\s/)) {
        if (!inList || listType !== "ul") {
          if (inList) output.push(listType === "ul" ? "</ul>" : "</ol>");
          output.push("<ul>");
          inList = true;
          listType = "ul";
        }
        output.push(`<li>${this.inlineMarkdown(line.replace(/^\s*[-*]\s/, ""))}</li>`);
        i++;
        continue;
      }

      // Ordered list
      if (line.match(/^\s*\d+\.\s/)) {
        if (!inList || listType !== "ol") {
          if (inList) output.push(listType === "ul" ? "</ul>" : "</ol>");
          output.push("<ol>");
          inList = true;
          listType = "ol";
        }
        output.push(`<li>${this.inlineMarkdown(line.replace(/^\s*\d+\.\s/, ""))}</li>`);
        i++;
        continue;
      }

      // Table
      if (line.includes("|") && i + 1 < lines.length && lines[i + 1]?.match(/^\|?\s*[-:]+/)) {
        const tableLines: string[] = [];
        while (i < lines.length && lines[i].includes("|")) {
          tableLines.push(lines[i]);
          i++;
        }
        output.push(this.parseTable(tableLines));
        continue;
      }

      // Empty line
      if (!line.trim()) {
        i++;
        continue;
      }

      // Paragraph
      const paraLines: string[] = [line];
      i++;
      while (i < lines.length && lines[i].trim() && !lines[i].startsWith("#") && !lines[i].startsWith("```") && !lines[i].startsWith(">") && !lines[i].match(/^[-*]\s/) && !lines[i].match(/^\d+\.\s/) && !lines[i].match(/^---/)) {
        paraLines.push(lines[i]);
        i++;
      }
      output.push(`<p>${this.inlineMarkdown(paraLines.join(" "))}</p>`);
    }

    if (inList) {
      output.push(listType === "ul" ? "</ul>" : "</ol>");
    }

    return output.join("\n");
  }

  private inlineMarkdown(text: string): string {
    return text
      // Bold + italic
      .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
      // Bold
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      // Italic
      .replace(/\*(.+?)\*/g, "<em>$1</em>")
      // Inline code
      .replace(/`([^`]+)`/g, "<code>$1</code>")
      // Links
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  }

  private parseTable(lines: string[]): string {
    if (lines.length < 2) return "";
    const parseRow = (line: string) =>
      line.split("|").map((c) => c.trim()).filter(Boolean);

    const headers = parseRow(lines[0]);
    const rows = lines.slice(2).map(parseRow);

    const headerHtml = headers.map((h) => `<th>${this.inlineMarkdown(h)}</th>`).join("");
    const bodyHtml = rows
      .map((row) => `<tr>${row.map((c) => `<td>${this.inlineMarkdown(c)}</td>`).join("")}</tr>`)
      .join("\n");

    return `<table>\n<thead><tr>${headerHtml}</tr></thead>\n<tbody>\n${bodyHtml}\n</tbody>\n</table>`;
  }
}
